### PR TITLE
Upgrade prost crates to 0.13

### PR DESCRIPTION
**Pull request by nickpresta**
Upgrade to the latest `prost` version (`0.13`):

- https://crates.io/crates/prost
- https://crates.io/crates/prost-types
- https://crates.io/crates/prost-build

Closes https://github.com/fdeantoni/prost-wkt/issues/67

### CODE REVIEW

**Comment by nickpresta** [comment]
@fdeantoni Don't intend to pressure you - just wanted to let you know this PR exists and ask whether there's anything else I need to do as part of this change (e.g. CHANGELOG entry). Thanks!

**Comment by fdeantoni** [comment]
Many thanks for putting this PR together! I will review and if all looks good will try to create a new release in the next few days.

**Comment by ytitov** [comment]
no pressure

**Comment by djc** [comment]
@fdeantoni friendly ping? Would be nice to get this released!

**Comment by fdeantoni** [comment]
Hi all, apologies for the delay! I will make sure to push out an update this weekend.

**Comment by h7kanna** [comment]
Should this be 0.6 release? Seems like updating the prost to 0.13 is breaking builds.

```
59   | #[derive(Clone, PartialEq, ::prost::Message)]
     |                            ^^^^^^^^^^^^^^^^ the trait `prost::Message` is not implemented for `prost_wkt_types::Duration`
     |
     = help: the following other types implement trait `prost::Message`:
               ()
               Acceptance
               Access
               AccountAccess
               ActivityExecutionResult
               ActivityFailureInfo
               ActivityHeartbeat
               ActivityPropertiesModifiedExternallyEventAttributes
             and 535 others
note: required by a bound in `prost::encoding::message::merge`
    --> /Users/h7kanna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-0.12.6/src/encoding.rs:1075:12

```

**Comment by djc** [comment]
Yup, this should definitely get a semver-incompatible release (and you probably want to yank 0.5.2).

**Comment by fdeantoni** [comment]
Were all the dependencies updated to Prost 0.13 and prost-wkt to 0.5.2? Although Prost has gone to 0.13, the implementation of prost-wkt has not changed significantly, hence I kept it at 0.5. I realize now that this may cause problems and it should go to 0.6. I will yank this release and make it 0.6.0 instead. Apologies for all the trouble caused!

**Comment by fdeantoni** [comment]
Hi All, I have yanked 0.5.2 and released it as 0.6.0 instead. I've added a `CHANGELOG.md` to document this as well. Please test it out and if any other problems encountered do let me know!!

**Comment by h7kanna** [comment]
prost-wkt-build needs to be yanked as well
```
[[package]]
name = "prost-wkt-build"
version = "0.5.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a06feedac9f90870ab1c46ac404cf3217ba42d220c62ff8f8119d4b1f685741c"
dependencies = [
 "heck 0.5.0",
 "prost 0.13.1",
 "prost-build 0.13.1",
 "prost-types 0.13.1",
 "quote",
]
```

**Comment by fdeantoni** [comment]
Apologies yes, `prost-wkt-build` and `prost-wkt-types` have been yanked now as well.

**Comment by h7kanna** [comment]
All good now, Thank you.

**Pull request merged**
