### PR TITLE
Update prost from 0.11.9 to 0.12.0

### PR DESCRIPTION
**Pull request by dragonnn**
In my use case and by running test I didn't notice with pushing prost to 0.12.0 any problems.

### CODE REVIEW

**Comment by fdeantoni** [comment]
Many thanks for putting together this PR! I was planning to release a new version in the next two weeks. I did notice that Prost now has a version 0.12.1 (also in crates.io), so we might want to go straight for that one instead. Also need a little more time to investigate why the build fails at 1.62. It looks like minimum required will be 1.63 now...

**Comment by dragonnn** [comment]
Just pushed prost up to 0.12.1. When it comes to MSRV I am perfectly fine with needing 1.63. In the project I am using prost-wkt I do use current stable and update it regularly so that doesn't affect me.

**Comment by Leulz** [comment]
FYI #54 has an error that is happening when one uses prost-wkt with the latest version of prost (0.12.1). I'm also having the same error.

Just saying this here to avoid potential problems with bumping the prost version of the crate. Maybe prost introduced a breaking change that does not have a test here to catch it? Not sure, but though you all should know.

**Comment by dragonnn** [comment]
> FYI #54 has an error that is happening when one uses prost-wkt with the latest version of prost (0.12.1). I'm also having the same error.
> 
> Just saying this here to avoid potential problems with bumping the prost version of the crate. Maybe prost introduced a breaking change that does not have a test here to catch it? Not sure, but thought you all should know.

No, this is just how rust works, when you pull current prost-wkt into a project that uses prost 0.12.1 you have two prost version in your project, 0.11 with prost-wkt implements and 0.12.1 with your project uses, so yes then you get errors of stuff not implemented because prost structs implement it for 0.11, not 0.12.
They where for sure some breaking changes in 0.12 with is why the version bump was made, but they don't affect prost-wkt.

**Comment by Leulz** [comment]
> > FYI #54 has an error that is happening when one uses prost-wkt with the latest version of prost (0.12.1). I'm also having the same error.
> > Just saying this here to avoid potential problems with bumping the prost version of the crate. Maybe prost introduced a breaking change that does not have a test here to catch it? Not sure, but thought you all should know.
> 
> No, this is just how rust works, when you pull current prost-wkt into a project that uses prost 0.12.1 you have two prost version in your project, 0.11 with prost-wkt implements and 0.12.1 with your project uses, so yes then you get errors of stuff not implemented because prost structs implement it for 0.11, not 0.12. They where for sure some breaking changes in 0.12 with is why the version bump was made, but they don't affect prost-wkt.

I see, thanks for the reply! Hopefully we'll be having this PR merged soon, then. I introduced an implementation of TryFrom<i32> for prost's enums and wanted to use it in my projects.

**Comment by dsmith3197** [comment]
@fdeantoni Is there anything blocking releasing the new version on crates.io?

**Pull request merged**
